    - name: "Instala pacotes de dependencia do sistema Operacional"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - mysql-server
        - python-mysqldb
      become: yes

    - name: "Cria o BD Mysql DB"
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present
      become: yes

    - name: "Create database user with name bob"
      mysql_user:
        name: "{{ wp_user_name }}"
        password: "{{ wp_user_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      become: yes      
      with_items:
        - "{{ wp_host_ip }}"

    - name: "Configura mysql para aceitar conexoes remotas"
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - restart mysql